feat: Query sharing s3
AltimateAI/vscode-dbt-power-user pull request #974
Opened 2024-03-08 11:50 UTC by gaurpulkit

- Modifying the existing Query Result Sharing PR by using a pre-signed s3 url to send the data directly to the user's s3 server instead of storing the data in Altimate's database.

2024-03-10 14:35 UTC, mdesmet commented
I think the point is to have both ways. We should offer the choice to the user to either use s3 bucket or use our saas.

@anandgupta42: Can you confirm?

2024-03-19 13:45 UTC, saravmajestic commented on src/webview_provider/queryResultPanel.ts
> +                title: "Generating Shareable URL",
add telemetry

2024-03-19 13:47 UTC, saravmajestic commented on src/webview_provider/queryResultPanel.ts
> +                    if (uploadResponse.status === 200) {
early returns

2024-03-19 13:47 UTC, saravmajestic commented on src/webview_provider/queryResultPanel.ts
> +                      if (verifyData.ok) {
early returns

2024-03-19 13:48 UTC, saravmajestic requested changes
some cleanup needed

2024-03-20 01:13 UTC, mdesmet commented on src/webview_provider/queryResultPanel.ts
> +                    if (uploadResponse.status === 200) {
Also http related stuff shouldn't leak into implementations.

2024-08-14 01:42 UTC, saravmajestic commented
Not needed anymore

2024-08-14 01:42 UTC, closed without merging